name: Build and Push Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/philipppollmann/telekom-project-launchpad/app:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=philipppollmann/telekom-project-launchpad
            org.opencontainers.image.author=philipppollmann